### ISSUE TITLE
What widget are you using for CPU etc. monitoring?

### ISSUE THREAD

**Issue by Cumol** [nnsnico/mybar#1]
Thank you for your bar widget!

I was wondering which widget you are using for your CPU and memory usage?

**Comment by nnsnico** [comment]
Thanks for posting the issue.

The tool name is gotop. It is not included in my bar widget.
[Here](https://github.com/xxxserxxx/gotop) is the repository on github.

**Comment by Cumol** [comment]
Thanks! For some reason I have troubles with the homebrew install but I guess this is not your problem :D
